name: CI/CD - Tienda Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push imagen Backend
        run: |
          docker build -t tienda-backend ./backend
          docker tag tienda-backend ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest

      - name: Deploy en EC2-APP via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --region ${{ secrets.AWS_REGION }} \
            --parameters 'commands=[
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REPO_URL_BACKEND }}:latest",
              "docker stop tienda-backend || true",
              "docker rm tienda-backend || true",
              "docker run -d --name tienda-backend -p 3001:3001 -e DB_HOST=10.0.131.190 -e DB_USER=root -e DB_PASSWORD=admin123 -e DB_NAME=tienda_perritos ${{ secrets.ECR_REPO_URL_BACKEND }}:latest"
            ]'
